import assert from 'node:assert/strict'
import { mkdirSync, mkdtempSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import test from 'node:test'
import { inspect } from './check.mjs'
import { renderReport } from './report.mjs'
import { materialize, rules } from './rules.mjs'

const IDS = rules.map((row) => row[0])

test('catalog is the 56 signed checks', () => {
  assert.equal(IDS.length, 56)
  assert.equal(new Set(IDS).size, 56)
  for (const rule of rules.map(materialize)) {
    assert.notEqual(rule.severity, 'review')
    assert.ok(rule.title.length > 8)
    if (rule.pattern) new RegExp(rule.pattern, 'g')
  }
})

test('each signed check fires on a planted issue', () => {
  const root = tempRepo()
  write(root, 'probe/secrets.js', [
    'const key = "AKIAIOSFODNN7EXAMPLE"',
    'const pem = "-----BEGIN PRIVATE KEY-----"',
    'const slack = "xoxb-FAKE000000-not-real"',
    'const github = "ghp_abcdefghijklmnopqrst"',
    'const stripe = "sk_live_abcdefghij"',
    'const npmToken = "npm_abcdefghijklmnopqrst"',
    'const password = "supersecret1"',
    'const url = "postgres://user:pass@host/db"',
    'eval("1")',
    'new Function("return 1")',
    'el.innerHTML = userInput',
    'document.write("x")',
    'import { exec } from "child_process"',
    'exec("echo probe")',
    'const headers = { "Access-Control-Allow-Origin": "*" }',
    'const token = { alg: "none" }',
    'md5(password)',
    'postMessage("x", "*")',
    'localStorage.setItem("k", "bearer probe-token")',
    'const endpoint = "http://example.com/api"',
    'const total = parseFloat(price)',
    'try { risky() } catch (e) {}',
    'console.log("probe")',
    'debugger',
    'const pending = "TODO probe"',
    'throw new Error("TODO")',
    'res.send(err.stack)',
    'throw new Error("Not implemented")',
    '// const kept = 1',
    '// let other = 2',
    '// function removed() {}',
    '// return kept',
    '// Generated by ChatGPT',
    'const NEXT_PUBLIC_API_KEY = "probe"',
    'const password = "admin123"',
    'logger.info(password)',
  ].join('\n'))
  write(root, 'probe/.env', 'PROBE=not-a-secret\n')
  write(root, 'probe/page.html', [
    '<a href="javascript:alert(1)">x</a>',
    '<a target="_blank" href="https://example.com">x</a>',
    '<button onclick="alert(1)">x</button>',
    '<p>Lorem ipsum</p>',
  ].join('\n'))
  write(root, 'probe/app.py', [
    'import os, pickle, yaml, requests',
    'os.system("echo probe")',
    'pickle.loads(blob)',
    'yaml.load(blob)',
    'requests.get("https://example.com", verify=False)',
    'requests.get("https://example.com")',
    'try:',
    '    risky()',
    'except Exception:',
    '    pass',
  ].join('\n'))
  write(root, 'probe/tls.go', 'package probe\nvar cfg = tls.Config{InsecureSkipVerify: true}\n')
  write(root, 'probe/up.sql', 'DROP TABLE users;\n')
  write(root, 'probe/node-tls.js', 'process.env.NODE_TLS_REJECT_UNAUTHORIZED = 0\n')
  write(root, 'package.json', JSON.stringify({
    dependencies: { wild: '*', gitdep: 'git+https://example.com/example.git', ranged: '^1.0.0' },
    engines: { node: '>=99' },
  }))
  write(root, '.github/workflows/ci.yml', [
    'jobs:',
    '  test:',
    '    steps:',
    '      - uses: actions/checkout@v4',
    '        # trivy is only mentioned here',
    '      - run: node --test',
    '        node-version: 22',
  ].join('\n'))
  write(root, 'probe/tests/focus.test.js', 'it.only("a", () => {})\nit.skip("b", () => {})\npage.waitForTimeout(1000)\n')
  write(root, 'probe/lint.js', '// eslint-disable-next-line no-eval\n')
  write(root, 'probe/cast.ts', '// @ts-expect-error probe\nexport const value = input as any\n')
  write(root, 'playwright.config.js', 'export default { webServer: { command: "npm run dev" } }\n')
  write(root, 'probe/long.js', `${'export const line = 1\n'.repeat(801)}`)
  const { findings, scopes } = inspect(root)
  const report = renderReport(findings, scopes)
  const missing = IDS.filter((id) => !findings.some((item) => item.id === id))
  assert.deepEqual(missing, [])
  assert.equal(report.rows.length, 56)
  assert.equal(report.markdown.includes('Not automated'), false)
  for (const secret of ['AKIA', 'user:pass', 'sk_live_', 'xoxb-', 'ghp_', 'checkout@v4', '^1.0.0']) {
    assert.equal(report.markdown.includes(secret), false, secret)
  }
})

test('signed corrections do not flag the safe case', () => {
  const root = tempRepo()
  write(root, 'safe.js', [
    'model.eval("score")',
    'el.innerHTML = "<p>ok</p>"',
    'socket.send(err.stack)',
    'const password = "admin123"',
  ].join('\n'))
  write(root, 'page.html', 'el.innerHTML = name\n')
  write(root, 'safe.py', 'yaml.load(data, Loader=yaml.SafeLoader)\nsubprocess.Popen(["ls"])\n')
  write(root, 'nearby.py', 'yaml.load(data)\n# SafeLoader\n')
  write(root, 'main.go', 'exec.Command("git", "status")\n')
  write(root, 'undoable.sql', 'DROP TABLE users;\n')
  write(root, 'down/001.sql', 'DROP TABLE users;\n')
  write(root, 'package.json', JSON.stringify({
    workspaces: ['packages/*'],
    dependencies: { left: '1.0.0' },
    engines: { node: '>=22' },
  }))
  write(root, 'package-lock.json', '{}\n')
  write(root, 'packages/a/package.json', JSON.stringify({ dependencies: { left: '^1.0.0' } }))
  write(root, 'other/pkg/package.json', JSON.stringify({ dependencies: { left: '^1.0.0' } }))
  write(root, '.github/dependabot.yml', 'version: 2\n')
  write(root, '.github/workflows/ci.yml', 'jobs:\n  test:\n    steps:\n      - run: echo ok\n        node-version: "22"\n')
  const findings = inspect(root).findings
  const ids = (file) => findings.filter((item) => item.file.endsWith(file)).map((item) => item.id)
  assert.equal(ids('safe.js').includes('V011'), false)
  assert.equal(ids('safe.js').includes('V014'), false)
  assert.equal(ids('safe.js').includes('V070'), false)
  assert.equal(ids('safe.js').includes('V007'), false)
  assert.equal(ids('page.html').includes('V014'), false)
  assert.equal(ids('safe.py').includes('V017'), false)
  assert.equal(ids('safe.py').includes('V016'), false)
  assert.ok(ids('nearby.py').includes('V017'))
  assert.equal(ids('main.go').includes('V016'), false)
  assert.ok(ids('undoable.sql').includes('V050'))
  assert.equal(ids('001.sql').includes('V050'), false)
  assert.equal(findings.some((item) => item.id === 'V053' && item.file === 'packages/a/package.json'), false)
  assert.ok(findings.some((item) => item.id === 'V053' && item.file === 'other/pkg/package.json'))
  assert.equal(findings.some((item) => item.id === 'V055'), false)
  assert.equal(findings.some((item) => item.id === 'V098'), false)
})

test('a repository without that language is not applicable', () => {
  const root = tempRepo()
  write(root, 'README.md', 'Lorem ipsum\n')
  const { findings, scopes } = inspect(root)
  const report = renderReport(findings, scopes)
  const row = (id) => report.rows.find((item) => item.id === id)
  assert.equal(row('V001').result, 'Pass')
  assert.equal(row('V011').result, 'Not applicable')
  assert.equal(row('V017').result, 'Not applicable')
  assert.equal(row('V018').result, 'Not applicable')
  assert.equal(row('V082').result, 'Not applicable')
  assert.equal(findings.some((item) => item.id === 'V082'), false)
  assert.equal(report.counts.Pass + report.counts.Suggestion + report.counts['Not applicable'], 56)
})

function tempRepo() {
  return mkdtempSync(join(tmpdir(), 'vibe-'))
}

function write(root, rel, text) {
  const file = join(root, rel)
  mkdirSync(join(file, '..'), { recursive: true })
  writeFileSync(file, text.endsWith('\n') ? text : `${text}\n`)
}
