import { execFileSync } from 'node:child_process'
import { existsSync, readFileSync, readdirSync } from 'node:fs'
import { join } from 'node:path'
import { isCode, isCommentLine, isGenerated, isGo, isHtmlish, isJs, isJsTs, isPy, isRb, isSql, isTestPath } from './files.mjs'

const LOCKS = ['package-lock.json', 'npm-shrinkwrap.json', 'yarn.lock', 'pnpm-lock.yaml', 'bun.lock', 'bun.lockb']
const CODE_COMMENT = /^\s*\/\/\s*(?:const|let|var|function|import|export|return|if|for|while|await|class|async)\b/
const PY_COMMENT = /^\s*#\s*(?:def|class|import|from|return|if|for|while|await)\b/
const AI_BANNER = /Generated by (?:ChatGPT|Claude|Copilot|Gemini|an AI)|generated by (?:ChatGPT|Claude|Copilot|Gemini|an AI)|This (?:code|file) was generated|this (?:code|file) was generated/

export function extraFindings(root, texts, rules) {
  const byId = new Map(rules.map((rule) => [rule.id, rule]))
  const findings = []
  const add = (id, file, line, extra = '') => {
    const rule = byId.get(id)
    if (!rule) return
    findings.push({ id, severity: rule.severity, title: rule.title, file, line, extra })
  }
  for (const { rel, text } of texts) {
    if (rel.endsWith('checks/vibe/rules.mjs') || rel.endsWith('checks/vibe/project.mjs')) continue
    perFile(rel, text, add)
  }
  repo(root, texts, add)
  for (const rel of markdownRels(root)) {
    if (texts.some((file) => file.rel === rel)) continue
    banner(rel, readFileSync(join(root, rel), 'utf8'), add)
  }
  return findings
}

function perFile(rel, text, add) {
  if (isTestPath(rel)) {
    return
  }
  if (isJsTs(rel)) innerHtml(rel, text, add)
  if (isHtmlish(rel)) blankTarget(rel, text, add)
  shell(rel, text, add)
  pickleYaml(rel, text, add)
  tls(rel, text, add)
  emptyCatch(rel, text, add)
  if (isSql(rel)) destructiveSql(rel, text, add)
  if (isPy(rel)) httpTimeout(rel, text, add)
  if (/(^|\/)(playwright|cypress)\.config\.[cm]?[jt]s$/.test(rel)) e2eServer(rel, text, add)
  if (isCode(rel) && !isGenerated(rel)) commentedCode(rel, text, add)
  if (rel.startsWith('.github/workflows/') && /\.ya?ml$/.test(rel)) actionPin(rel, text, add)
  banner(rel, text, add)
}

function innerHtml(rel, text, add) {
  const lines = text.split(/\r?\n/)
  for (let i = 0; i < lines.length; i += 1) {
    const match = lines[i].match(/\.innerHTML\s*=\s*(.*)$/)
    if (!match) continue
    const rhs = match[1].trim()
    if (/^['"][^'"]*['"]\s*;?\s*$/.test(rhs)) continue
    if (/^`[^`$]*`\s*;?\s*$/.test(rhs)) continue
    add('V014', rel, i + 1)
  }
}

function blankTarget(rel, text, add) {
  const lines = text.split(/\r?\n/)
  for (let i = 0; i < lines.length; i += 1) {
    if (!/target\s*=\s*['"]_blank['"]/.test(lines[i])) continue
    const window = lines.slice(i, i + 6).join('\n')
    const end = window.indexOf('>')
    const tag = end === -1 ? window : window.slice(0, end)
    if (!/noopener/.test(tag)) add('V024', rel, i + 1)
  }
}

function shell(rel, text, add) {
  const lines = text.split(/\r?\n/)
  const importsChildProcess = /child_process/.test(text)
  for (let i = 0; i < lines.length; i += 1) {
    if (isJs(rel)) {
      if (/child_process\.exec(?:Sync)?\s*\(/.test(lines[i]) || /(?<![\w.])execSync\s*\(/.test(lines[i])) {
        add('V016', rel, i + 1)
      } else if (importsChildProcess && /(?<![\w.])exec\s*\(/.test(lines[i])) {
        add('V016', rel, i + 1)
      }
    }
    if (!isPy(rel)) continue
    if (/os\.system\s*\(/.test(lines[i])) add('V016', rel, i + 1)
    if (/subprocess\.(?:Popen|run|call|check_output|check_call)\s*\(/.test(lines[i])) {
      const args = callText(lines, i)
      if (/shell\s*=\s*True/.test(args)) add('V016', rel, i + 1)
    }
  }
}

function pickleYaml(rel, text, add) {
  if (!isPy(rel)) return
  const lines = text.split(/\r?\n/)
  for (let i = 0; i < lines.length; i += 1) {
    if (/pickle\.loads?\s*\(/.test(lines[i])) add('V017', rel, i + 1)
    if (/yaml\.(?:unsafe_load|load)\s*\(/.test(lines[i])) {
      const args = callText(lines, i)
      if (!/SafeLoader|safe_load/.test(args)) add('V017', rel, i + 1)
    }
  }
}

function tls(rel, text, add) {
  const lines = text.split(/\r?\n/)
  for (let i = 0; i < lines.length; i += 1) {
    if (isPy(rel) && /verify\s*=\s*False/.test(lines[i])) add('V018', rel, i + 1)
    if (isJs(rel) && /NODE_TLS_REJECT_UNAUTHORIZED\s*=\s*['"]?0/.test(lines[i])) add('V018', rel, i + 1)
    if (isGo(rel) && /InsecureSkipVerify\s*:\s*true/.test(lines[i])) add('V018', rel, i + 1)
  }
}

function emptyCatch(rel, text, add) {
  const lines = text.split(/\r?\n/)
  for (let i = 0; i < lines.length; i += 1) {
    if (isJs(rel) && /\bcatch\s*(?:\([^)]*\))?/.test(lines[i])) {
      let start = i
      if (!lines[i].includes('{')) {
        if (lines[i + 1]?.includes('{')) start = i + 1
        else continue
      }
      const body = braceBody(lines, start)
      if (body.trim() === '') add('V061', rel, i + 1)
    }
    if (isPy(rel) && /^\s*except\b[^:]*:\s*$/.test(lines[i])) {
      const next = lines.slice(i + 1, i + 4).find((line) => line.trim())
      if (next && next.trim() === 'pass') add('V061', rel, i + 1)
    }
    if (isRb(rel) && /^\s*rescue\b/.test(lines[i])) {
      const next = lines.slice(i + 1).find((line) => line.trim())
      if (next && next.trim() === 'end') add('V061', rel, i + 1)
    }
  }
}

function callText(lines, index) {
  const start = lines[index].indexOf('(')
  if (start === -1) return lines[index]
  let depth = 0
  let text = ''
  for (let i = index; i < Math.min(lines.length, index + 8); i += 1) {
    const chunk = i === index ? lines[index].slice(start) : lines[i]
    text += chunk
    for (const char of chunk) {
      if (char === '(') depth += 1
      else if (char === ')') {
        depth -= 1
        if (depth === 0) return text
      }
    }
    text += '\n'
  }
  return text
}

function braceBody(lines, index) {
  let text = ''
  let depth = 0
  let started = false
  for (let i = index; i < Math.min(lines.length, index + 12); i += 1) {
    for (const char of lines[i]) {
      if (char === '{') {
        depth += 1
        started = true
      } else if (char === '}') {
        depth -= 1
        if (started && depth === 0) return text
      } else if (started) text += char
    }
    text += '\n'
  }
  return started ? text : 'kept'
}

function destructiveSql(rel, text, add) {
  if (isRollbackPath(rel)) return
  const lines = text.split(/\r?\n/)
  for (let i = 0; i < lines.length; i += 1) {
    const line = lines[i]
    if (/\bDROP\s+TABLE\b/i.test(line) || /\bTRUNCATE\b/i.test(line)) add('V050', rel, i + 1)
  }
}

function isRollbackPath(rel) {
  return rel.split('/').some((part) => {
    const stem = part.replace(/\.[^.]+$/, '').toLowerCase()
    return stem === 'down' || stem === 'rollback' || stem === 'undo'
  })
}

function httpTimeout(rel, text, add) {
  const lines = text.split(/\r?\n/)
  for (let i = 0; i < lines.length; i += 1) {
    if (!/requests\.(?:get|post|put|patch|delete|head)\s*\(/.test(lines[i])) continue
    const window = lines.slice(i, i + 8).join('\n')
    if (!/\btimeout\s*=/.test(window)) add('V067', rel, i + 1)
  }
}

function e2eServer(rel, text, add) {
  const lines = text.split(/\r?\n/)
  for (let i = 0; i < lines.length; i += 1) {
    if (/command\s*:.*\b(?:npm|pnpm|yarn)\s+run\s+dev\b/.test(lines[i])) add('V078', rel, i + 1)
    else if (/command\s*:.*\b(?:vite|next|ng)\s+dev\b/.test(lines[i])) add('V078', rel, i + 1)
    else if (/command\s*:.*\bvite\b/.test(lines[i]) && !/\bpreview\b|\bbuild\b/.test(lines[i])) add('V078', rel, i + 1)
  }
}

function commentedCode(rel, text, add) {
  const pattern = isPy(rel) ? PY_COMMENT : CODE_COMMENT
  if (!isPy(rel) && !isJs(rel)) return
  const lines = text.split(/\r?\n/)
  let run = 0
  let start = 0
  for (let i = 0; i < lines.length; i += 1) {
    if (pattern.test(lines[i])) {
      if (run === 0) start = i
      run += 1
    } else {
      if (run >= 4) add('V086', rel, start + 1, `${run} commented lines`)
      run = 0
    }
  }
  if (run >= 4) add('V086', rel, start + 1, `${run} commented lines`)
}

function banner(rel, text, add) {
  const lines = text.split(/\r?\n/)
  const limit = isCode(rel) ? lines.length : Math.min(lines.length, 15)
  for (let i = 0; i < limit; i += 1) {
    if (isCode(rel) && !isCommentLine(lines[i], rel)) continue
    if (AI_BANNER.test(lines[i])) add('V090', rel, i + 1)
  }
}

function actionPin(rel, text, add) {
  const lines = text.split(/\r?\n/)
  for (let i = 0; i < lines.length; i += 1) {
    const match = lines[i].match(/uses:\s*['"]?([^'"#\s]+)/)
    if (!match) continue
    const uses = match[1]
    if (uses.startsWith('./') || uses.startsWith('docker://')) continue
    if (uses.includes('/.github/workflows/')) continue
    const ref = uses.includes('@') ? uses.split('@')[1] : ''
    if (/^[0-9a-f]{40}$/.test(ref)) continue
    add('V056', rel, i + 1, 'action ref is not a commit SHA')
  }
}

function repo(root, texts, add) {
  const manifests = texts.filter((file) => file.rel === 'package.json' || file.rel.endsWith('/package.json'))
  if (manifests.length === 0) return
  const rootPkg = readPackage(join(root, 'package.json'))
  const rootLock = LOCKS.some((name) => existsSync(join(root, name)))
  for (const file of manifests) {
    const json = readPackage(join(root, file.rel))
    if (!json) continue
    const groups = { ...json.dependencies, ...json.devDependencies }
    if (Object.values(groups).some((version) => version === '*' || version === 'latest')) {
      add('V051', file.rel, 1, 'wildcard or latest')
    }
    if (Object.values(groups).some((version) => /^(git\+|github:|gitlab:)/.test(String(version)))) {
      add('V052', file.rel, 1, 'git dependency')
    }
    const dir = file.rel === 'package.json' ? '' : file.rel.slice(0, file.rel.lastIndexOf('/'))
    const beside = LOCKS.some((name) => existsSync(join(root, dir, name)))
    const covered = dir !== '' && rootLock && rootPkg && workspaceCovers(rootPkg, dir)
    if (!beside && !covered) {
      add('V053', file.rel, 1)
      if (Object.values(json.dependencies ?? {}).some((version) => isRange(version))) {
        add('V054', file.rel, 1, 'ranged production dependency')
      }
    }
  }
  advisory(root, add)
  if (rootPkg) ciNode(root, rootPkg, add)
}

function readPackage(file) {
  if (!existsSync(file)) return null
  try {
    return JSON.parse(readFileSync(file, 'utf8'))
  } catch {
    return null
  }
}

function workspaceCovers(pkg, dir) {
  const field = pkg.workspaces
  const patterns = Array.isArray(field) ? field : field?.packages ?? []
  return patterns.some((pattern) => {
    if (pattern.endsWith('/**')) return dir === pattern.slice(0, -3) || dir.startsWith(`${pattern.slice(0, -3)}/`)
    if (pattern.endsWith('/*')) {
      const prefix = pattern.slice(0, -2)
      return dir.startsWith(`${prefix}/`) && !dir.slice(prefix.length + 1).includes('/')
    }
    return pattern === dir
  })
}

function isRange(version) {
  const value = String(version).trim()
  if (value === '*' || value === 'latest' || value === '') return true
  return /^[\^~<>]|\|\||\bx\b|\*/.test(value)
}

function advisory(root, add) {
  const workflows = workflowFiles(root)
  if (existsSync(join(root, '.github/dependabot.yml'))) return
  const command = /\b(?:npm audit|pnpm audit|yarn audit|osv-scanner|pip-audit|cargo audit|govulncheck|trivy|snyk)\b/
  const configured = workflows.some((rel) =>
    readFileSync(join(root, rel), 'utf8')
      .split(/\r?\n/)
      .some((line) => !line.trim().startsWith('#') && command.test(line)),
  )
  if (!configured) add('V055', workflows[0] ?? 'package.json', 1)
}

function ciNode(root, json, add) {
  if (!json.engines?.node) return
  const floor = nodeFloor(json.engines.node)
  if (floor == null) return
  const workflows = workflowFiles(root)
  if (workflows.length === 0) {
    add('V098', 'package.json', 1, 'engines declares Node and CI does not')
    return
  }
  const majors = new Set()
  for (const rel of workflows) {
    const yaml = readFileSync(join(root, rel), 'utf8')
    for (const match of yaml.matchAll(/node(?:-version)?:\s*\[([^\]]+)\]/g)) {
      for (const number of match[1].matchAll(/\d+/g)) majors.add(Number(number[0]))
    }
    for (const match of yaml.matchAll(/node-version:\s*['"]?(\d+)/g)) majors.add(Number(match[1]))
  }
  if (majors.size === 0) {
    add('V098', workflows[0], 1, 'CI does not select Node')
    return
  }
  if (![...majors].some((major) => major >= floor)) add('V098', workflows[0], 1, 'CI Node is below engines')
}

function nodeFloor(engines) {
  const match = String(engines ?? '').match(/(\d+)/)
  return match ? Number(match[1]) : null
}

function workflowFiles(root) {
  const dir = join(root, '.github/workflows')
  if (!existsSync(dir)) return []
  return readdirSync(dir)
    .filter((name) => /\.ya?ml$/.test(name))
    .map((name) => `.github/workflows/${name}`)
}

function markdownRels(root) {
  try {
    const out = execFileSync('git', ['ls-files', '-z', '--', '*.md', '*.mdx'], {
      cwd: root,
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'ignore'],
    })
    return out.split('\0').filter(Boolean)
  } catch {
    return []
  }
}
