/** One hundred vibe-coding mistakes. Patterns are high-confidence only. The rest are a review list. */
export const rules = [
  ['V001', 'Secrets', 'error', 'AWS access key in source', 'AKIA[0-9A-Z]{16}'],
  ['V002', 'Secrets', 'error', 'Private key block committed', 'BEGIN (?:RSA |OPENSSH |EC )?PRIVATE KEY'],
  ['V003', 'Secrets', 'error', 'Slack token in source', 'xox[baprs]-[A-Za-z0-9-]{10,}'],
  ['V004', 'Secrets', 'error', 'GitHub token in source', 'ghp_[A-Za-z0-9]{20,}|github_pat_[A-Za-z0-9_]{20,}'],
  ['V005', 'Secrets', 'error', 'Stripe live secret in source', 'sk_live_[A-Za-z0-9]{10,}'],
  ['V006', 'Secrets', 'error', 'npm token in source', 'npm_[A-Za-z0-9]{20,}'],
  ['V007', 'Secrets', 'error', 'Hardcoded password assignment', '(?:[Pp]assword|[Pp]asswd|[Ss]ecret)\\s*[:=]\\s*[\'"][^\'"]{8,}[\'"]'],
  ['V008', 'Secrets', 'error', 'Connection string with embedded credentials', '[a-z][a-z0-9+.-]*://[^\\s\'"]+:[^\\s\'"@]+@'],
  ['V009', 'Secrets', 'error', 'Tracked .env file', null, 'tracked-env'],
  ['V010', 'Secrets', 'review', 'Secret scanned in git history, not only the worktree'],
  ['V011', 'Execution', 'error', 'eval() of a string', '(?<![\\w.])eval\\s*\\('],
  ['V012', 'Execution', 'error', 'new Function() from a string', 'new\\s+Function\\s*\\('],
  ['V013', 'Execution', 'error', 'dangerouslySetInnerHTML', 'dangerouslySetInnerHTML'],
  ['V014', 'Execution', 'error', 'innerHTML assignment', '\\.innerHTML\\s*='],
  ['V015', 'Execution', 'error', 'document.write', 'document\\.write\\s*\\('],
  ['V016', 'Execution', 'error', 'Shell exec of a command string', '(?<![\\w.])execSync\\s*\\(|(?<![\\w.])exec\\s*\\('],
  ['V017', 'Execution', 'error', 'Unsafe pickle or YAML load', 'pickle\\.loads\\s*\\(|yaml\\.load\\s*\\('],
  ['V018', 'Execution', 'error', 'TLS verification turned off', 'verify\\s*=\\s*False|NODE_TLS_REJECT_UNAUTHORIZED\\s*=\\s*[\'"]?0'],
  ['V019', 'Execution', 'error', 'javascript: URL', 'javascript\\s*:'],
  ['V020', 'Execution', 'review', 'User input passed into a shell, SQL string, or HTML sink'],
  ['V021', 'Web', 'error', 'CORS allows every origin', 'Access-Control-Allow-Origin[\'"]?\\s*[:=]\\s*[\'"]\\*'],
  ['V022', 'Web', 'error', 'JWT accepted with algorithm none', 'alg[\'"]?\\s*[:=]\\s*[\'"]none[\'"]'],
  ['V023', 'Web', 'error', 'Password hashed with MD5 or SHA-1', '(?:md5|sha1|MD5|SHA1)\\s*\\([^)]*[Pp]assword'],
  ['V024', 'Web', 'warning', 'target=_blank without rel=noopener', 'target\\s*=\\s*[\'"]_blank[\'"](?![^>]*noopener)'],
  ['V025', 'Web', 'warning', 'postMessage to any origin', 'postMessage\\s*\\([^)]*,\\s*[\'"]\\*[\'"]'],
  ['V026', 'Web', 'warning', 'Token or password written to localStorage', 'localStorage\\.setItem\\s*\\([^)]*(?:token|password|secret)'],
  ['V027', 'Web', 'warning', 'Insecure http URL in application source', 'http://(?!\\$\\{|localhost|127\\.0\\.0\\.1|\\[::1\\])(?![^\\s\'"]*\\.localhost)'],
  ['V028', 'Web', 'warning', 'Inline HTML event handler', '\\sonclick\\s*='],
  ['V029', 'Web', 'review', 'Cookie set without Secure, HttpOnly, and SameSite'],
  ['V030', 'Web', 'review', 'Open redirect from a user-supplied URL'],
  ['V031', 'Auth', 'review', 'Authorization checked only in the UI'],
  ['V032', 'Auth', 'review', 'Missing server-side check on every privileged action'],
  ['V033', 'Auth', 'review', 'Password reset or magic link does not expire after one use'],
  ['V034', 'Auth', 'review', 'OAuth or login flow has no state parameter'],
  ['V035', 'Auth', 'review', 'Session fixation or a session id in the URL'],
  ['V036', 'Auth', 'review', 'Account enumeration through different error messages'],
  ['V037', 'Auth', 'review', 'No rate limit on login, reset, or signup'],
  ['V038', 'Auth', 'review', 'CSRF protection missing on cookie-authenticated writes'],
  ['V039', 'Auth', 'review', 'Admin routes share the same client bundle checks as user routes'],
  ['V040', 'Auth', 'review', 'Logged-out and wrong-tenant states are not tested'],
  ['V041', 'Data', 'warning', 'SQL built by string concatenation', '(?:SELECT|select)[\\s\\S]{0,80}\\+|(?:INSERT|insert)[\\s\\S]{0,40}\\+|query\\s*\\(\\s*[\'"`][^\'"`]*\\$\\{'],
  ['V042', 'Data', 'review', 'Tenant or owner id taken from the client instead of the session'],
  ['V043', 'Data', 'review', 'Unique business keys enforced only in application code'],
  ['V044', 'Data', 'review', 'Required columns are nullable'],
  ['V045', 'Data', 'review', 'Multi-step writes are not in a transaction'],
  ['V046', 'Data', 'review', 'Webhook or payment handler is not idempotent'],
  ['V047', 'Data', 'review', 'List endpoint has no limit'],
  ['V048', 'Data', 'review', 'Money stored or compared as a float'],
  ['V049', 'Data', 'review', 'Card numbers, full account numbers, or secrets stored in the database'],
  ['V050', 'Data', 'review', 'Migration can destroy data with no restore drill'],
  ['V051', 'Dependencies', 'error', 'Dependency pinned to * or latest', null, 'dep-range'],
  ['V052', 'Dependencies', 'warning', 'Git URL used as a dependency', null, 'git-dep'],
  ['V053', 'Dependencies', 'review', 'Lockfile missing or not committed'],
  ['V054', 'Dependencies', 'review', 'Production dependencies not exactly pinned'],
  ['V055', 'Dependencies', 'review', 'npm audit or an equivalent advisory check is not in CI'],
  ['V056', 'Dependencies', 'review', 'GitHub Actions not pinned to a commit SHA'],
  ['V057', 'Dependencies', 'review', 'Install scripts from new packages were not read'],
  ['V058', 'Dependencies', 'review', 'A new dependency was added for a few lines of code'],
  ['V059', 'Dependencies', 'review', 'Major upgrades landed in the same change as a feature'],
  ['V060', 'Dependencies', 'review', 'License of a new dependency was not checked'],
  ['V061', 'Reliability', 'warning', 'Empty catch block', 'catch\\s*(?:\\([^)]*\\))?\\s*\\{\\s*\\}'],
  ['V062', 'Reliability', 'warning', 'console.log left in application source', 'console\\.log\\s*\\('],
  ['V063', 'Reliability', 'error', 'debugger statement', '(?<![\\w.])debugger\\b'],
  ['V064', 'Reliability', 'warning', 'TODO or FIXME left in source', '\\b(?:TODO|FIXME|todo|fixme)\\b'],
  ['V065', 'Reliability', 'warning', 'Not implemented placeholder', 'not implemented|Not implemented|throw new Error\\([\'"]TODO'],
  ['V066', 'Reliability', 'review', 'Happy path has no loading or error state'],
  ['V067', 'Reliability', 'review', 'Outbound calls have no timeout'],
  ['V068', 'Reliability', 'review', 'Retries are unbounded or not idempotent'],
  ['V069', 'Reliability', 'review', 'Failure leaves partial writes behind'],
  ['V070', 'Reliability', 'review', 'Errors fail open, or stack traces are shown to users'],
  ['V071', 'Tests', 'error', 'Focused test left in (.only)', '\\b(?:it|test|describe)\\.only\\s*\\(|\\bfdescribe\\s*\\('],
  ['V072', 'Tests', 'warning', 'Skipped test left in', '\\b(?:it|test|describe)\\.skip\\s*\\(|\\bxit\\s*\\(|\\bxdescribe\\s*\\('],
  ['V073', 'Tests', 'warning', 'Lint rule disabled', 'eslint-disable'],
  ['V074', 'Tests', 'warning', 'Type error suppressed', '@ts-ignore|@ts-expect-error|@ts-nocheck'],
  ['V075', 'Tests', 'warning', 'as any cast', '\\bas\\s+any\\b'],
  ['V076', 'Tests', 'review', 'Tests assert the implementation instead of the behavior'],
  ['V077', 'Tests', 'review', 'No test for the empty, error, or unauthorized state'],
  ['V078', 'Tests', 'review', 'End-to-end tests hit the dev server instead of the production build'],
  ['V079', 'Tests', 'review', 'A test sleeps to wait for a result'],
  ['V080', 'Tests', 'review', 'AI-written tests were not read before they were trusted'],
  ['V081', 'Slop', 'warning', 'Source file longer than 800 lines', null, 'long-file'],
  ['V082', 'Slop', 'warning', 'Lorem ipsum placeholder copy', '[Ll]orem [Ii]psum'],
  ['V083', 'Slop', 'warning', 'Placeholder throw', 'throw new Error\\([\'"]Not implemented'],
  ['V084', 'Slop', 'review', 'The author cannot explain the control flow they are shipping'],
  ['V085', 'Slop', 'review', 'Two styles of the same job in one change (callbacks and async, two HTTP clients)'],
  ['V086', 'Slop', 'review', 'Dead code, unused flags, or commented-out blocks'],
  ['V087', 'Slop', 'review', 'Generic names that hide the domain (data, item, temp, foo)'],
  ['V088', 'Slop', 'review', 'A framework default was kept where the product needed a decision'],
  ['V089', 'Slop', 'review', 'README describes a different app than the one in the repo'],
  ['V090', 'Slop', 'review', 'An AI footer or "generated by" banner was left in the diff'],
  ['V091', 'Shipping', 'review', 'A secret can end up in the client bundle'],
  ['V092', 'Shipping', 'review', 'Debug mode or a default password works in production'],
  ['V093', 'Shipping', 'review', 'Source maps for production are public without a reason'],
  ['V094', 'Shipping', 'review', 'No health check for the process that users actually hit'],
  ['V095', 'Shipping', 'review', 'No backup and no practiced restore'],
  ['V096', 'Shipping', 'review', 'No rollback that does not depend on the broken deploy'],
  ['V097', 'Shipping', 'review', 'Logs include tokens, passwords, or full payment payloads'],
  ['V098', 'Shipping', 'review', 'CI does not run on the same Node or runtime you ship'],
  ['V099', 'Shipping', 'review', 'Dependency review is not required on pull requests'],
  ['V100', 'Shipping', 'review', 'An AI-produced diff was opened or merged with no human review'],
]

export function materialize(row) {
  const [id, category, severity, title, pattern, kind] = row
  return { id, category, severity, title, pattern: pattern ?? null, kind: kind ?? (pattern ? 'regex' : 'review') }
}
