/** Fifty-six signed checks. Human-review ids are not in this catalog. */

export const rules = [
  ['V001', 'Secrets', 'error', 'AWS access key in source', 'AKIA[0-9A-Z]{16}'],
  ['V002', 'Secrets', 'error', 'Private key block committed', 'BEGIN (?:RSA |OPENSSH |EC )?PRIVATE KEY'],
  ['V003', 'Secrets', 'error', 'Slack token in source', 'xox[baprs]-[A-Za-z0-9-]{10,}'],
  ['V004', 'Secrets', 'error', 'GitHub token in source', 'ghp_[A-Za-z0-9]{20,}|github_pat_[A-Za-z0-9_]{20,}'],
  ['V005', 'Secrets', 'error', 'Stripe live secret in source', 'sk_live_[A-Za-z0-9]{10,}'],
  ['V006', 'Secrets', 'error', 'npm token in source', 'npm_[A-Za-z0-9]{20,}'],
  ['V007', 'Secrets', 'error', 'Hardcoded password assignment', '(?:[Pp]assword|[Pp]asswd|[Ss]ecret)\\s*[:=]\\s*[\'"][^\'"]{8,}[\'"]'],
  ['V008', 'Secrets', 'error', 'Connection string with embedded credentials', '[a-z][a-z0-9+.-]*://[^\\s\'"]+:[^\\s\'"@]+@'],
  ['V009', 'Secrets', 'error', 'Tracked .env file', null, 'tracked-env'],
  ['V011', 'Execution', 'error', 'eval() of a string', '(?<![\\w.])eval\\s*\\('],
  ['V012', 'Execution', 'error', 'new Function() from a string', 'new\\s+Function\\s*\\('],
  ['V014', 'Execution', 'warning', 'innerHTML assignment', null, 'inner-html'],
  ['V015', 'Execution', 'warning', 'document.write', 'document\\.write\\s*\\('],
  ['V016', 'Execution', 'warning', 'Shell exec of a command string', null, 'shell'],
  ['V017', 'Execution', 'warning', 'Unsafe pickle or YAML load', null, 'pickle-yaml'],
  ['V018', 'Execution', 'warning', 'TLS verification turned off', null, 'tls'],
  ['V019', 'Execution', 'error', 'javascript: URL', 'javascript\\s*:'],
  ['V021', 'Web', 'error', 'CORS allows every origin', 'Access-Control-Allow-Origin[\'"]?\\s*[:=]\\s*[\'"]\\*'],
  ['V022', 'Web', 'error', 'JWT accepted with algorithm none', 'alg[\'"]?\\s*[:=]\\s*[\'"]none[\'"]'],
  ['V023', 'Web', 'error', 'Password hashed with MD5 or SHA-1', '(?:md5|sha1|MD5|SHA1)\\s*\\([^)]*[Pp]assword'],
  ['V024', 'Web', 'warning', 'target=_blank without rel=noopener', null, 'blank-target'],
  ['V025', 'Web', 'warning', 'postMessage to any origin', 'postMessage\\s*\\([^)]*,\\s*[\'"]\\*[\'"]'],
  ['V026', 'Web', 'warning', 'Token or password written to localStorage', 'localStorage\\.setItem\\s*\\(\\s*[\'"][^\'"]*[\'"]\\s*,\\s*[\'"](?:sk_live_|sk_test_|ghp_|github_pat_|xox[baprs]-|npm_|bearer )[^\'"]*[\'"]'],
  ['V027', 'Web', 'warning', 'Insecure http URL in application source', 'http://(?!\\$\\{|localhost|127\\.0\\.0\\.1|\\[::1\\]|www\\.w3\\.org)(?![^\\s\'"]*\\.localhost)'],
  ['V028', 'Web', 'warning', 'Inline HTML event handler', '\\sonclick\\s*=\\s*[\'"]'],
  ['V048', 'Data', 'warning', 'Money stored or compared as a float', 'parseFloat\\s*\\(\\s*(?:price|amount|balance|subtotal|cost)\\b|\\b(?:price|amount|balance|subtotal|cost)\\s+(?:FLOAT|float|DOUBLE|double|REAL|real)\\b'],
  ['V050', 'Data', 'warning', 'Destructive DROP or TRUNCATE in a forward migration', null, 'destructive-sql'],
  ['V051', 'Dependencies', 'error', 'Dependency pinned to * or latest', null, 'dep-range'],
  ['V052', 'Dependencies', 'warning', 'Git URL used as a dependency', null, 'git-dep'],
  ['V053', 'Dependencies', 'warning', 'Lockfile missing or not committed', null, 'lockfile'],
  ['V054', 'Dependencies', 'warning', 'Production dependency range with no lockfile', null, 'dep-pin'],
  ['V055', 'Dependencies', 'warning', 'npm audit or an equivalent advisory check is not in CI', null, 'audit-ci'],
  ['V056', 'Dependencies', 'warning', 'GitHub Actions not pinned to a commit SHA', null, 'action-pin'],
  ['V061', 'Reliability', 'warning', 'Empty catch block', null, 'empty-catch'],
  ['V062', 'Reliability', 'warning', 'console.log left in application source', 'console\\.log\\s*\\('],
  ['V063', 'Reliability', 'error', 'debugger statement', '(?<![\\w.])debugger\\b'],
  ['V064', 'Reliability', 'warning', 'TODO or FIXME left in source', '\\b(?:TODO|FIXME|todo|fixme)\\b'],
  ['V065', 'Reliability', 'warning', 'Not implemented placeholder', 'throw new Error\\([\'"](?:TODO|Not implemented)|raise NotImplementedError'],
  ['V067', 'Reliability', 'warning', 'Outbound calls have no timeout', null, 'http-timeout'],
  ['V070', 'Reliability', 'warning', 'Stack trace sent on a response', '\\b(?:res|resp|response|reply)\\.(?:send|json|end)\\s*\\([^)\\n]{0,120}\\.stack\\b'],
  ['V071', 'Tests', 'error', 'Focused test left in (.only)', '\\b(?:it|test|describe)\\.only\\s*\\(|\\bfdescribe\\s*\\('],
  ['V072', 'Tests', 'warning', 'Skipped test left in', '\\b(?:it|test|describe)\\.skip\\s*\\(|\\bxit\\s*\\(|\\bxdescribe\\s*\\('],
  ['V073', 'Tests', 'warning', 'Lint rule disabled', 'eslint-disable'],
  ['V074', 'Tests', 'warning', 'Type error suppressed', '@ts-ignore|@ts-expect-error|@ts-nocheck'],
  ['V075', 'Tests', 'warning', 'as any cast', '\\bas\\s+any\\b'],
  ['V078', 'Tests', 'warning', 'End-to-end tests hit the dev server instead of the production build', null, 'e2e-server'],
  ['V079', 'Tests', 'warning', 'A test sleeps to wait for a result', 'waitForTimeout\\s*\\(|\\bcy\\.wait\\s*\\(\\s*\\d|\\btime\\.sleep\\s*\\(|\\basyncio\\.sleep\\s*\\(|\\bThread\\.sleep\\s*\\('],
  ['V081', 'Slop', 'warning', 'Source file longer than 800 lines', null, 'long-file'],
  ['V082', 'Slop', 'warning', 'Lorem ipsum placeholder copy', '[Ll]orem [Ii]psum'],
  ['V083', 'Slop', 'warning', 'Placeholder throw', 'throw new Error\\([\'"]Not implemented'],
  ['V086', 'Slop', 'warning', 'Commented-out code left in source', null, 'commented-code'],
  ['V090', 'Slop', 'warning', 'An AI footer or generated-by banner was left in', null, 'ai-banner'],
  ['V091', 'Shipping', 'warning', 'A secret can end up in the client bundle', '\\b(?:VITE_|NEXT_PUBLIC_|REACT_APP_|PUBLIC_)[A-Z0-9_]*(?:SECRET|TOKEN|PASSWORD|PRIVATE_KEY|API_KEY)\\b'],
  ['V092', 'Shipping', 'warning', 'Debug mode or a default password works in production', '(?:[Pp]assword|[Pp]asswd)\\s*[:=]\\s*[\'"](?:password|admin|admin123|123456|changeme)[\'"]|\\bdebug\\s*=\\s*True\\b'],
  ['V097', 'Shipping', 'warning', 'Logs include tokens, passwords, or full payment payloads', '(?:console\\.(?:log|debug|info|warn|error)|logger\\.(?:log|debug|info|warn|error))\\s*\\([^)\\n]{0,160}(?:[Pp]assword|[Pp]asswd|[Ss]ecret|apiKey|api_key|accessToken|[Aa]uthorization)'],
  ['V098', 'Shipping', 'warning', 'CI does not run on the same Node or runtime you ship', null, 'ci-node'],
]

export function materialize(row) {
  const [id, category, severity, title, pattern, kind] = row
  return { id, category, severity, title, pattern: pattern ?? null, kind: kind ?? (pattern ? 'regex' : 'check') }
}
